Repository deckhouse/sds-node-configurator, pull requests merged in 2024-07, with the labels that each got.

#63 [controller] Added free space field to LVMVolumeGroup VG and ThinPools
  crds/doc-ru-lvmvolumegroup.yaml
  crds/lvmlogicalvolume.yaml
  crds/lvmvolumegroup.yaml
  images/agent/api/v1alpha1/lvm_volume_group.go
  images/agent/internal/type.go
  images/agent/pkg/controller/lvm_logical_volume_watcher.go
  images/agent/pkg/controller/lvm_logical_volume_watcher_func.go
  images/agent/pkg/controller/lvm_logical_volume_watcher_test.go
  images/agent/pkg/controller/lvm_volume_group_discover.go
  images/agent/pkg/controller/lvm_volume_group_discover_test.go
  images/agent/pkg/controller/lvm_volume_group_watcher_func.go
  images/sds-health-watcher-controller/api/v1alpha1/lvm_volume_group.go
  images/sds-health-watcher-controller/pkg/controller/lvg_status_watcher.go
Labels: enhancement

#64 Move golang models to separate module
  api/go.mod
  api/go.sum
  api/v1alpha1/block_device.go
  api/v1alpha1/lvm_logical_volume.go
  api/v1alpha1/lvm_volume_group.go
  api/v1alpha1/register.go
  api/v1alpha1/zz_generated.deepcopy.go
Labels: enhancement

#66 [controller] Move LVMVolumeGroup resource deletion logic from Discover to Watcher
  images/agent/pkg/controller/block_device.go
  images/agent/pkg/controller/lvm_logical_volume_watcher.go
  images/agent/pkg/controller/lvm_volume_group_discover.go
  images/agent/pkg/controller/lvm_volume_group_watcher.go
  images/agent/pkg/controller/lvm_volume_group_watcher_constants.go
  images/agent/pkg/controller/lvm_volume_group_watcher_func.go
Labels: enhancement

#67 [controller] Use models from separate module
  images/agent/Dockerfile
  images/agent/api/v1alpha1/block_device.go
  images/agent/api/v1alpha1/lvm_logical_volume.go
  images/agent/api/v1alpha1/lvm_volume_group.go
  images/agent/api/v1alpha1/register.go
  images/agent/api/v1alpha1/zz_generated.deepcopy.go
  images/agent/cmd/main.go
  images/agent/config/config.go
  images/agent/go.mod
  images/agent/go.sum
  images/agent/pkg/cache/cache.go
  images/agent/pkg/cache/cache_test.go
  images/agent/pkg/controller/block_device.go
  images/agent/pkg/controller/block_device_test.go
  images/agent/pkg/controller/controller_reconcile_test.go
  images/agent/pkg/controller/controller_suite_test.go
  images/agent/pkg/controller/lvm_logical_volume_bench_test.go
  images/agent/pkg/controller/lvm_logical_volume_watcher.go
  images/agent/pkg/controller/lvm_logical_volume_watcher_func.go
  images/agent/pkg/controller/lvm_logical_volume_watcher_test.go
  images/agent/pkg/controller/lvm_volume_group_discover.go
  images/agent/pkg/controller/lvm_volume_group_discover_test.go
  images/agent/pkg/controller/lvm_volume_group_test.go
  images/agent/pkg/controller/lvm_volume_group_watcher.go
  images/agent/pkg/controller/lvm_volume_group_watcher_func.go
  images/agent/pkg/controller/lvm_volume_group_watcher_test.go
  images/agent/pkg/scanner/scanner.go
  images/agent/pkg/utils/commands.go
  images/agent/pkg/utils/commands_test.go
  images/sds-health-watcher-controller/Dockerfile
  images/sds-health-watcher-controller/api/v1alpha1/lvm_volume_group.go
  images/sds-health-watcher-controller/api/v1alpha1/register.go
  images/sds-health-watcher-controller/api/v1alpha1/zz_generated.deepcopy.go
  images/sds-health-watcher-controller/cmd/main.go
  images/sds-health-watcher-controller/go.mod
  images/sds-health-watcher-controller/go.sum
  images/sds-health-watcher-controller/pkg/controller/lvg_conditions_watcher.go
  images/sds-health-watcher-controller/pkg/controller/lvg_conditions_watcher_funcs.go
  images/sds-health-watcher-controller/pkg/controller/lvg_status_watcher.go
  images/sds-health-watcher-controller/pkg/controller/sds_infra_watcher_funcs.go
  images/sds-health-watcher-controller/pkg/controller/sds_infra_watcher_test.go
Labels: enhancement

#68 [docs] update lvmvolumegroup
  crds/doc-ru-lvmvolumegroup.yaml
  crds/lvmvolumegroup.yaml
Labels: documentation

#69 [docs] Add README.md for golang API module
  api/README.md
Labels: documentation

#71 [controller] Change type for Spec.Size field of LVMVolumeGroup and LVMLogicalVolume from Quantity to String
  api/v1alpha1/lvm_logical_volume.go
  api/v1alpha1/lvm_volume_group.go
  crds/lvmlogicalvolume.yaml
  crds/lvmvolumegroup.yaml
Labels: enhancement

#72 [controller] Make the controller be able to work with percent ThinPool and LV sizes
  images/agent/go.mod
  images/agent/go.sum
  images/agent/internal/const.go
  images/agent/pkg/controller/lvm_logical_volume_watcher.go
  images/agent/pkg/controller/lvm_logical_volume_watcher_func.go
  images/agent/pkg/controller/lvm_volume_group_discover.go
  images/agent/pkg/controller/lvm_volume_group_watcher.go
  images/agent/pkg/controller/lvm_volume_group_watcher_func.go
  images/agent/pkg/utils/commands.go
  images/sds-health-watcher-controller/go.mod
  images/sds-health-watcher-controller/go.sum
  images/sds-health-watcher-controller/internal/const.go
  images/sds-health-watcher-controller/pkg/controller/lvg_conditions_watcher.go
Labels: enhancement

#73 [controller] add liveness and readiness checks
  images/agent/cmd/main.go
  images/agent/config/config.go
  images/sds-health-watcher-controller/cmd/main.go
  images/sds-health-watcher-controller/config/config.go
  templates/agent/daemonset.yaml
  templates/sds-health-watcher-controller/deployment.yaml
Labels: enhancement

#75 [controller] Fix a block device extension
  images/agent/pkg/controller/lvm_volume_group_watcher_func.go
Labels: bug

#74 [controller] Add an auto extension feature for LVMVolumeGroup thin-pools and LVMLogicalVolumes
  crds/doc-ru-lvmlogicalvolume.yaml
  crds/doc-ru-lvmvolumegroup.yaml
  crds/lvmlogicalvolume.yaml
  crds/lvmvolumegroup.yaml
  images/agent/cmd/main.go
  images/agent/go.mod
  images/agent/go.sum
  images/agent/internal/const.go
  images/agent/pkg/cache/cache.go
  images/agent/pkg/controller/lvm_logical_volume_bench_test.go
  images/agent/pkg/controller/lvm_logical_volume_extender_watcher.go
  images/agent/pkg/controller/lvm_logical_volume_watcher.go
  images/agent/pkg/controller/lvm_logical_volume_watcher_func.go
  images/agent/pkg/controller/lvm_logical_volume_watcher_test.go
  images/agent/pkg/controller/lvm_volume_group_discover.go
  images/agent/pkg/controller/lvm_volume_group_watcher.go
  images/agent/pkg/controller/lvm_volume_group_watcher_func.go
  images/agent/pkg/scanner/scanner.go
  images/agent/pkg/utils/commands.go
Labels: enhancement

#77 [docs] Fix tag key in FAQ
  docs/FAQ.md
  docs/FAQ_RU.md
Labels: documentation

#11 [monitoring] Add metrics collectors
  images/agent/README.md
  images/agent/config/config.go
  images/agent/config/config_test.go
  images/sds-health-watcher-controller/config/config.go
  images/sds-health-watcher-controller/config/config_test.go
  templates/agent/daemonset.yaml
  templates/agent/podmonitor.yaml
  templates/sds-health-watcher-controller/deployment.yaml
  templates/sds-health-watcher-controller/servicemonitor.yaml
Labels: enhancement

#78 [CI] Fixed runners and added dev registry cleanup
  .github/workflows/build_dev.yml
  .github/workflows/build_prod.yml
  .github/workflows/checks.yaml
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_prod.yml
  .github/workflows/dev_registry-cleanup.yml
  werf_cleanup.yaml
Labels: enhancement
