Repository deckhouse/sds-node-configurator, pull requests merged in 2024-01, with the labels that each got.

#12 [ci] Add check if any label is assined to new PR
  .github/workflows/checks.yaml
Labels: release-note/ignore

#15 [docs] Fix badge, improve docs and descriptions in CRDs
  .werf/bundle.yaml
  crds/blockdevices.yaml
  crds/doc-ru-blockdevices.yaml
  crds/doc-ru-lvmvolumegroup.yaml
  crds/lvmvolumegroup.yaml
  docs/CONFIGURATION.md
  docs/CONFIGURATION_RU.md
  docs/CR.md
  docs/CR_RU.md
  docs/FAQ.md
  docs/FAQ_RU.md
  docs/README.MD
  docs/README.md
  docs/README_RU.md
  docs/USAGE.md
  docs/USAGE_RU.md
Labels: documentation, release-note/ignore

#18 [controller] Fix MD RAID block device discovery by reading UUID instead of serial
  images/agent/pkg/controller/block_device.go
Labels: bug

#17 [docs] Add label documentation in checks.yaml
  .github/workflows/checks.yaml
Labels: bug
