Repository deckhouse/sds-node-configurator, pull requests merged in 2024-08, with the labels that each got.

#79 [CI] Add golang tests and linter launch
  .github/workflows/go_lint.yaml
  .github/workflows/go_tests.yaml
  .golangci.yaml
Labels: enhancement

#80 [controller] Code refactor by linter suggestions
  api/v1alpha1/register.go
  api/v1alpha1/zz_generated.deepcopy.go
  images/agent/src/pkg/controller/block_device.go
Labels: enhancement

#82 [CI] Check Go modules version
  .github/workflows/go_modules_check.yaml
  images/agent/src/go.mod
  images/agent/src/go.sum
  images/sds-health-watcher-controller/src/go.mod
  images/sds-health-watcher-controller/src/go.sum
Labels: enhancement

#83 [CI] Add an action to notify about "freezed" PRs.
  .github/scripts/fetch_prs.mjs
  .github/scripts/package.json
  .github/workflows/prs-summary.yml
Labels: enhancement

#81 [controller] Refactor code on linter issues and test improvements.
  .golangci.yaml
  images/agent/src/cmd/main.go
  images/agent/src/config/config.go
  images/agent/src/config/config_test.go
  images/agent/src/go.mod
  images/agent/src/go.sum
  images/agent/src/internal/type.go
  images/agent/src/pkg/cache/cache.go
  images/agent/src/pkg/cache/cache_test.go
  images/agent/src/pkg/controller/block_device.go
  images/agent/src/pkg/controller/block_device_test.go
  images/agent/src/pkg/controller/controller_reconcile_test.go
  images/agent/src/pkg/controller/controller_suite_test.go
  images/agent/src/pkg/controller/lvm_logical_volume_bench_test.go
  images/agent/src/pkg/controller/lvm_logical_volume_extender_watcher.go
  images/agent/src/pkg/controller/lvm_logical_volume_watcher.go
  images/agent/src/pkg/controller/lvm_logical_volume_watcher_func.go
  images/agent/src/pkg/controller/lvm_logical_volume_watcher_test.go
  images/agent/src/pkg/controller/lvm_volume_group_discover.go
  images/agent/src/pkg/controller/lvm_volume_group_discover_test.go
  images/agent/src/pkg/controller/lvm_volume_group_test.go
  images/agent/src/pkg/controller/lvm_volume_group_watcher.go
  images/agent/src/pkg/controller/lvm_volume_group_watcher_func.go
  images/agent/src/pkg/controller/lvm_volume_group_watcher_test.go
  images/agent/src/pkg/kubutils/kubernetes.go
  images/agent/src/pkg/logger/logger.go
  images/agent/src/pkg/monitoring/monitoring.go
  images/agent/src/pkg/scanner/scanner.go
  images/agent/src/pkg/utils/commands.go
  images/agent/src/pkg/utils/commands_test.go
  images/sds-health-watcher-controller/src/cmd/main.go
  images/sds-health-watcher-controller/src/config/config.go
  images/sds-health-watcher-controller/src/config/config_test.go
  images/sds-health-watcher-controller/src/go.mod
  images/sds-health-watcher-controller/src/go.sum
  images/sds-health-watcher-controller/src/pkg/controller/lvg_conditions_watcher.go
  images/sds-health-watcher-controller/src/pkg/controller/lvg_conditions_watcher_funcs.go
  images/sds-health-watcher-controller/src/pkg/controller/lvg_conditions_watcher_test.go
  images/sds-health-watcher-controller/src/pkg/controller/lvg_status_watcher.go
  images/sds-health-watcher-controller/src/pkg/controller/mc_watcher.go
  images/sds-health-watcher-controller/src/pkg/controller/sds_infra_watcher.go
  images/sds-health-watcher-controller/src/pkg/controller/sds_infra_watcher_funcs.go
  images/sds-health-watcher-controller/src/pkg/controller/sds_infra_watcher_test.go
  images/sds-health-watcher-controller/src/pkg/kubutils/kubernetes.go
  images/sds-health-watcher-controller/src/pkg/logger/logger.go
  images/sds-health-watcher-controller/src/pkg/monitoring/monitoring.go
  images/sds-utils-installer/src/cmd/main.go
Labels: enhancement

#86 [docs] Fixes in ru docs
  openapi/doc-ru-config-values.yaml
Labels: documentation

#85 [CI] Add Trivy vulnerables check
  .github/workflows/trivy_check.yaml
  images/agent/werf.inc.yaml
  images/sds-utils-installer/werf.inc.yaml
Labels: enhancement

#87 [controller] Fix internal hook and reduce image size
  .werf/bundle.yaml
  .werf/python-deps.yaml
  hooks/lib/module/module.py
  images/sds-health-watcher-controller/src/api/module_config.go
  images/sds-health-watcher-controller/src/api/register.go
  images/sds-health-watcher-controller/src/api/zz_generated.deepcopy.go
  images/sds-health-watcher-controller/src/api/zz_generated.defaults.go
  images/sds-health-watcher-controller/src/cmd/main.go
  images/sds-health-watcher-controller/src/go.mod
  images/sds-health-watcher-controller/src/go.sum
  images/sds-health-watcher-controller/src/pkg/controller/mc_watcher.go
Labels: bug

#76 [controller] Add labels to BlockDevices
  images/agent/src/pkg/controller/block_device.go
  images/agent/src/pkg/controller/block_device_test.go
  images/agent/src/pkg/controller/lvm_volume_group_watcher.go
  images/agent/src/pkg/controller/lvm_volume_group_watcher_func.go
  images/agent/src/pkg/controller/lvm_volume_group_watcher_test.go
Labels: enhancement

#89 [controller] Fix a bug with labels containing spaces.
  images/agent/src/go.mod
  images/agent/src/go.sum
  images/agent/src/internal/const.go
  images/agent/src/pkg/controller/block_device.go
  images/agent/src/pkg/controller/block_device_test.go
  images/agent/src/pkg/controller/controller_reconcile_test.go
Labels: bug
