Repository deckhouse/sds-node-configurator, pull requests merged in 2024-02, with the labels that each got.

#21 [controller] Fix naming bug by removing previous partUUID fix. Refactor name generation. Add test for device name.
  images/agent/pkg/controller/block_device.go
  images/agent/pkg/controller/block_device_test.go
Labels: bug

#14 [controller] Add a LVMLogicalVolumeWatcher controller
  crds/lvmlogicalvolume.yaml
  images/agent/cmd/bc/main.go
  images/agent/config/config.go
  images/agent/internal/const.go
  images/agent/pkg/controller/lvm_logical_volume_watcher.go
  images/agent/pkg/controller/lvm_logical_volume_watcher_test.go
  images/agent/pkg/controller/lvm_volume_group_discover.go
  images/agent/pkg/controller/lvm_volume_group_discover_test.go
  images/agent/pkg/controller/lvm_volume_group_watcher.go
  images/agent/pkg/controller/lvm_volume_group_watcher_func.go
  images/agent/pkg/utils/commands.go
  templates/agent/daemonset.yaml
Labels: enhancement

#24 [controller] add func AreSizesEqualWithinDelta
  images/agent/pkg/controller/lvm_logical_volume_watcher.go
Labels: bug, enhancement

#25 [controller] Fix resize for thinPools
  images/agent/pkg/controller/lvm_logical_volume_watcher.go
  images/agent/pkg/controller/lvm_volume_group_watcher.go
  images/agent/pkg/controller/lvm_volume_group_watcher_func.go
  images/agent/pkg/utils/units.go
Labels: bug

#26 [controller] Add tests to LvmLogicalVolumeWatcher controller.
  images/agent/pkg/controller/lvm_logical_volume_watcher_test.go
Labels: enhancement
