Repository deckhouse/sds-node-configurator, pull requests merged in 2024-11, with the labels that each got.

#103 [docs] Add license to api module
  api/LICENSE
Labels: documentation

#99 [controller] Add LVMVolumeGroupSet
  api/v1alpha1/lvm_volume_group_set.go
  api/v1alpha1/register.go
  api/v1alpha1/zz_generated.deepcopy.go
  crds/doc-ru-lvmvolumegroup.yaml
  crds/doc-ru-lvmvolumegroupset.yaml
  crds/lvmvolumegroupset.yaml
  images/agent/src/go.mod
  images/agent/src/internal/const.go
  images/agent/src/pkg/controller/lvm_volume_group_discover.go
  images/agent/src/pkg/controller/lvm_volume_group_discover_test.go
  images/agent/src/pkg/controller/lvm_volume_group_watcher.go
  images/agent/src/pkg/controller/lvm_volume_group_watcher_func.go
  images/agent/src/pkg/controller/lvm_volume_group_watcher_test.go
  images/agent/werf.inc.yaml
  images/sds-health-watcher-controller/src/cmd/main.go
  images/sds-health-watcher-controller/src/go.mod
  images/sds-health-watcher-controller/src/go.sum
  images/sds-health-watcher-controller/src/pkg/controller/block_device_labels_watcher.go
  images/sds-health-watcher-controller/src/pkg/controller/lvm_volume_group_set_watcher.go
  images/sds-health-watcher-controller/werf.inc.yaml
  images/sds-utils-installer/werf.inc.yaml
  templates/agent/daemonset.yaml
  templates/sds-health-watcher-controller/rbac-for-us.yaml
Labels: enhancement

#104 [internal] Add backup control label
  crds/blockdevices.yaml
  crds/lvmlogicalvolume.yaml
  crds/lvmvolumegroup.yaml
  crds/lvmvolumegroupbackup.yaml
  crds/lvmvolumegroupset.yaml
  images/agent/src/go.mod
  images/sds-health-watcher-controller/src/go.mod
Labels: enhancement

#105 [docs] Fix indentation for the spec.actualVGNameOnTheNode field
  docs/USAGE.md
  docs/USAGE_RU.md
Labels: bug, documentation
