Repository deckhouse/sds-node-configurator, pull requests merged in 2024-06, with the labels that each got.

#57 [docs] Change the module status to preview
  docs/README.md
  docs/README_RU.md
Labels: release-note/ignore

#58 [ci] Add previous channel release version check
  .github/check_previous_channel_release.sh
  .github/workflows/deploy_prod.yml
Labels: enhancement

#59 [controller] Fix thin-pool requested size validation and NotReady status
  images/agent/internal/const.go
  images/agent/pkg/controller/block_device.go
  images/agent/pkg/controller/lvm_volume_group_discover.go
  images/agent/pkg/controller/lvm_volume_group_watcher.go
  images/agent/pkg/controller/lvm_volume_group_watcher_func.go
  images/sds-health-watcher-controller/internal/const.go
  images/sds-health-watcher-controller/pkg/controller/lvg_conditions_watcher.go
  images/sds-health-watcher-controller/pkg/controller/sds_infra_watcher_funcs.go
Labels: bug

#61 [controller] Add AllocationLimit to LVMVolumeGroup resources and Contiguous to LVMLogicalVolume resources
  .github/workflows/deploy_dev.yml
  crds/doc-ru-lvmlogicalvolume.yaml
  crds/lvmlogicalvolume.yaml
  crds/lvmvolumegroup.yaml
  images/agent/api/v1alpha1/lvm_logical_volume.go
  images/agent/api/v1alpha1/lvm_volume_group.go
  images/agent/api/v1alpha1/register.go
  images/agent/cmd/main.go
  images/agent/go.mod
  images/agent/go.sum
  images/agent/internal/const.go
  images/agent/internal/type.go
  images/agent/pkg/cache/cache.go
  images/agent/pkg/controller/lvm_logical_volume_bench_test.go
  images/agent/pkg/controller/lvm_logical_volume_watcher.go
  images/agent/pkg/controller/lvm_logical_volume_watcher_func.go
  images/agent/pkg/controller/lvm_logical_volume_watcher_test.go
  images/agent/pkg/controller/lvm_volume_group_discover.go
  images/agent/pkg/controller/lvm_volume_group_discover_test.go
  images/agent/pkg/controller/lvm_volume_group_test.go
  images/agent/pkg/controller/lvm_volume_group_watcher.go
  images/agent/pkg/controller/lvm_volume_group_watcher_func.go
  images/agent/pkg/utils/commands.go
  images/sds-health-watcher-controller/api/v1alpha1/lvm_volume_group.go
  images/sds-health-watcher-controller/go.mod
  images/sds-health-watcher-controller/go.sum
  templates/agent/rbac.yaml
Labels: enhancement
