Repository deckhouse/sds-node-configurator, pull requests merged in 2025-01, with the labels that each got.

#117 [internal] Prepare to CSE 1.67
  .github/workflows/trivy_check.yaml
  .werf/consts.yaml
  .werf/images.yaml
  .werf/release.yaml
  api/go.mod
  api/go.sum
  charts/deckhouse_lib_helm-1.1.3.tgz
  charts/deckhouse_lib_helm-1.41.0.tgz
  images/agent/src/go.mod
  images/agent/src/go.sum
  images/agent/werf.inc.yaml
  images/sds-health-watcher-controller/src/go.mod
  images/sds-health-watcher-controller/src/go.sum
  images/sds-health-watcher-controller/werf.inc.yaml
  images/sds-utils-installer/werf.inc.yaml
  templates/agent/daemonset.yaml
  tools/dev_images/additional_tools/binary_replace.sh
  werf.yaml
Labels: enhancement

#119 [controller] Add dm_snapshot loading
  templates/agent/daemonset.yaml
Labels: bug

#121 [docs] Add labels list for BlockDevice
  .gitignore
  docs/FAQ.md
  docs/FAQ_RU.md
Labels: documentation

#118 [internal] Migrate to ALT P11
  .github/workflows/build_dev.yml
  images/agent/src/go.mod
  images/agent/werf.inc.yaml
  images/sds-health-watcher-controller/src/go.mod
  images/sds-health-watcher-controller/src/pkg/kubutils/kubernetes.go
  images/sds-health-watcher-controller/werf.inc.yaml
  images/sds-utils-installer/werf.inc.yaml
Labels: enhancement

#102 [docs] Configuration examples
  docs/CONFIGURATION.ru.md
  docs/CR.ru.md
  docs/FAQ.md
  docs/FAQ.ru.md
  docs/LAYOUTS.md
  docs/LAYOUTS.ru.md
  docs/README.ru.md
  docs/USAGE.ru.md
  docs/images/sds-node-configurator-scenaries.png
  docs/images/sds-node-configurator-scenaries.puml
  docs/images/sds-node-configurator-scenaries.ru.png
  docs/images/sds-node-configurator-scenaries.ru.puml
Labels: bug, documentation
